### ISSUE TITLE
quantifier after set-statement produces de.uka.ilkd.key.java.ConvertException

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1085]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1085) where the discussions are preserved.
    
----
    
* Mantis: [MT-1593](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1593)
* Submitted on: 2017-01-20 by (at)wpfeifer
* Updated: 2017-01-20

### Description

> If you try to use a quantifier expression to set a ghost field (via JML's set-statement), a ConvertException occurs (tested for \sum, \max, \prod, \forall, \exists).
> 
> Workaround is to define a model method, which returns the desired sum and call it in the set-statement.

### Steps to reproduce

```
//@ ghost \bigint value;
//@ ghost boolean flag;

in constructor:
//@ set value = (\sum int i; 0 <= i && i < 10, 1);
//@ set flag = (\forall int i; 0 <= i && i < 10; true);

-> file fails to load, example error message (shortened at (...)):

de.uka.ilkd.key.java.ConvertException: de.uka.ilkd.key.speclang.translation.SLTranslationException: Encountered "\\" at line 1, column 9.
Was expecting one of:
    <DL_EMBEDDED_FUNCTION> ...
    <MAP_FUNCTION> ...
    "++" ...
    (...)

     (recoder.ParserException)
	at de.uka.ilkd.key.java.Recoder2KeY.reportError(Recoder2KeY.java:1306)
	at de.uka.ilkd.key.java.Recoder2KeY.recoderCompilationUnitsAsFiles(Recoder2KeY.java:411)
	at de.uka.ilkd.key.java.Recoder2KeY.readCompilationUnitsAsFiles(Recoder2KeY.java:353)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.readJava(ProblemInitializer.java:311)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:507)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:497)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.createInitConfig(AbstractProblemLoader.java:396)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.load(AbstractProblemLoader.java:237)
	at de.uka.ilkd.key.proof.io.ProblemLoader.doWork(ProblemLoader.java:78)
	at de.uka.ilkd.key.proof.io.ProblemLoader.access$0(ProblemLoader.java:76)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:124)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:1)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: de.uka.ilkd.key.speclang.translation.SLTranslationException: Encountered "\\" at line 1, column 9.
Was expecting one of:
    <DL_EMBEDDED_FUNCTION> ...
    <MAP_FUNCTION> ...
    "++" ...
    (...)

     (recoder.ParserException)
	at de.uka.ilkd.key.java.recoderext.JMLTransformer.makeExplicit(JMLTransformer.java:725)
	at de.uka.ilkd.key.java.recoderext.RecoderModelTransformer.transform(RecoderModelTransformer.java:280)
	at recoder.kit.TwoPassTransformation.execute(TwoPassTransformation.java:100)
	at de.uka.ilkd.key.java.Recoder2KeY.transformModel(Recoder2KeY.java:865)
	at de.uka.ilkd.key.java.Recoder2KeY.recoderCompilationUnitsAsFiles(Recoder2KeY.java:405)
	... 16 more
Caused by: de.uka.ilkd.key.speclang.translation.SLTranslationException: Encountered "\\" at line 1, column 9.
Was expecting one of:
    <DL_EMBEDDED_FUNCTION> ...
    <MAP_FUNCTION> ...
    "++" ...
    (...)

     (recoder.ParserException)
	at de.uka.ilkd.key.java.recoderext.JMLTransformer.transformSetStatement(JMLTransformer.java:466)
	at de.uka.ilkd.key.java.recoderext.JMLTransformer.transformClasslevelComments(JMLTransformer.java:535)
	at de.uka.ilkd.key.java.recoderext.JMLTransformer.makeExplicit(JMLTransformer.java:696)
	... 20 more
Caused by: recoder.ParserException: Encountered "\\" at line 1, column 9.
Was expecting one of:
    <DL_EMBEDDED_FUNCTION> ...
    <MAP_FUNCTION> ...
    "++" ...
    (...)
    
	at de.uka.ilkd.key.java.recoderext.ProofJavaProgramFactory.parseStatements(ProofJavaProgramFactory.java:351)
	at recoder.java.JavaProgramFactory.parseStatements(JavaProgramFactory.java:750)
	at de.uka.ilkd.key.java.recoderext.JMLTransformer.transformSetStatement(JMLTransformer.java:459)
	... 22 more
Caused by: de.uka.ilkd.key.parser.proofjava.ParseException: Encountered "\\" at line 1, column 9.
Was expecting one of:
    <DL_EMBEDDED_FUNCTION> ...
    <MAP_FUNCTION> ...
    "++" ...
    (...)
    
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.generateParseException(ProofJavaParser.java:11380)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.jj_consume_token(ProofJavaParser.java:11248)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.UnaryExpression(ProofJavaParser.java:3383)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.MultiplicativeExpression(ProofJavaParser.java:3292)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.AdditiveExpression(ProofJavaParser.java:3249)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.ShiftExpression(ProofJavaParser.java:3206)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.RelationalExpression(ProofJavaParser.java:3157)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.InstanceOfExpression(ProofJavaParser.java:3135)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.EqualityExpression(ProofJavaParser.java:3093)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.AndExpression(ProofJavaParser.java:3063)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.ExclusiveOrExpression(ProofJavaParser.java:3033)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.InclusiveOrExpression(ProofJavaParser.java:3003)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.ConditionalAndExpression(ProofJavaParser.java:2973)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.ConditionalOrExpression(ProofJavaParser.java:2943)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.ConditionalExpression(ProofJavaParser.java:2914)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.Expression(ProofJavaParser.java:2815)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.PrimaryPrefix(ProofJavaParser.java:3885)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.PrimaryExpression(ProofJavaParser.java:3658)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.PostfixExpression(ProofJavaParser.java:3590)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.UnaryExpressionNotPlusMinus(ProofJavaParser.java:3451)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.UnaryExpression(ProofJavaParser.java:3369)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.MultiplicativeExpression(ProofJavaParser.java:3292)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.AdditiveExpression(ProofJavaParser.java:3249)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.ShiftExpression(ProofJavaParser.java:3206)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.RelationalExpression(ProofJavaParser.java:3157)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.InstanceOfExpression(ProofJavaParser.java:3135)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.EqualityExpression(ProofJavaParser.java:3093)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.AndExpression(ProofJavaParser.java:3063)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.ExclusiveOrExpression(ProofJavaParser.java:3033)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.InclusiveOrExpression(ProofJavaParser.java:3003)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.ConditionalAndExpression(ProofJavaParser.java:2973)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.ConditionalOrExpression(ProofJavaParser.java:2943)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.ConditionalExpression(ProofJavaParser.java:2914)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.Expression(ProofJavaParser.java:2815)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.StatementExpression(ProofJavaParser.java:4961)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.Statement(ProofJavaParser.java:4521)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.BlockStatement(ProofJavaParser.java:4803)
	at de.uka.ilkd.key.parser.proofjava.ProofJavaParser.GeneralizedStatements(ProofJavaParser.java:5502)
	at de.uka.ilkd.key.java.recoderext.ProofJavaProgramFactory.parseStatements(ProofJavaProgramFactory.java:345)
	... 24 more

```

### Additional Information

```
JML supports the use of quantifiers after set as specified here:
http://www.eecs.ucf.edu/~leavens/JML/jmlrefman/jmlrefman_13.html#SEC176
http://www.eecs.ucf.edu/~leavens/JML/jmlrefman/jmlrefman_12.html#SEC128
http://www.eecs.ucf.edu/~leavens/JML/jmlrefman/jmlrefman_12.html#SEC153
```

## History

* (at)wpfeifer -- (`NEW_BUG`) _2017-01-20_

## Attributes

* Category: JML Parser
* Status: NEW
* Severity: MINOR
* OS: 
* Target Version: 2.6
* Resolution: OPEN
* Priority: LOW
* Reproducibility: ALWAYS
* Platform: 
* Commit: 16f223425df855c1d2d6ea4f0600cc919c79f2e3
* Build: 
* Tags []
* Labels:  ~JML Parser  ~Bug  ~LOW  
* Version: _2.6_ 

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1593)
    
----
    
Information: 
* created_at: 2017-05-29T02:55:37.178Z
* updated_at: 2022-10-13T12:20:49.782Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by wadoon** [comment]
should be solved by #3400
