### ISSUE TITLE
NullpointerException with the counter example generator

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#130]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/130) where the discussions are preserved.
    
----
    
* Mantis: [MT-1520](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1520)
* Submitted on: 2015-01-16 by (at)mulbrich
* Updated: 2015-01-16

* Assigned to: (at)herda

### Description

> The attached example raises an NPE

### Steps to reproduce

```
Load the attached file, press Go and then the CEG-Button on the single remaining
open goal.
```

### Additional Information

```
"Exception for Z3_CE applied on Goal 249."

java.lang.NullPointerException

java.lang.NullPointerException
	at de.uka.ilkd.key.smt.lang.SMTTermMultOp.<init>(SMTTermMultOp.java:155)
	at de.uka.ilkd.key.smt.lang.SMTTerm.defaultMultOp(SMTTerm.java:403)
	at de.uka.ilkd.key.smt.lang.SMTTerm.implies(SMTTerm.java:608)
	at de.uka.ilkd.key.smt.SMTObjTranslator.addTypeConstarints(SMTObjTranslator.java:1561)
	at de.uka.ilkd.key.smt.SMTObjTranslator.generateTypeConstraints(SMTObjTranslator.java:1433)
	at de.uka.ilkd.key.smt.SMTObjTranslator.translateProblem(SMTObjTranslator.java:1133)
	at de.uka.ilkd.key.smt.SMTObjTranslator.translateProblem(SMTObjTranslator.java:478)
	at de.uka.ilkd.key.smt.SMTSolverImplementation.translateToCommand(SMTSolverImplementation.java:349)
	at de.uka.ilkd.key.smt.SMTSolverImplementation.run(SMTSolverImplementation.java:251)
	at java.lang.Thread.run(Thread.java:745)

```

## Files

  
`A.java`:

```java
class A {

int[] arg;
int offset;

/*@ ensures offset == arg[0]; */
void m() {
arg[0] = 0;
}
}

```

## History

* (at)mulbrich -- (`NEW_BUG`) _2015-01-16_

* (at)mulbrich -- (`NORMAL_TYPE`) _2015-01-16_

* (at)mulbrich -- (`NORMAL_TYPE`) _2015-01-16_

* (at)mulbrich -- (`FILE_ADDED`) _2015-01-16_

## Attributes

* Category: Counter Example Generator
* Status: ASSIGNED
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: RANDOM
* Platform: 
* Commit: 5d1492b0f9e723203ef645f327602ea32ba8039a
* Build: 
* Tags []
* Labels:  ~Counter Example Generator  ~Bug  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1520)
    
----
    
Information: 
* created_at: 2017-05-29T02:29:56.271Z
* updated_at: 2017-05-29T02:29:56.600Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Fixed in recent KeY
