### ISSUE TITLE
The exception dialog only presents half its message unless resized

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1310]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1310) where the discussions are preserved.
    
----
    
* Mantis: [MT-1457](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1457)
* Submitted on: 2014-06-26 by (at)mulbrich
* Updated: 2014-06-26

### Description

> The exception dialog tells very little (no error message) until the window is resized. Only then, the actual error message is printed!
> 

### Steps to reproduce

```
I could reproduce it on my input; however it is difficult to reproduce otherwise.

I attach the stack trace which may help in bug finding.
(class de.uka.ilkd.key.proof.io.ProblemLoaderException)
de.uka.ilkd.key.proof.io.ProblemLoaderException: unexpected token: elect2 (antlr.NoViableAltException)
	at de.uka.ilkd.key.proof.io.DefaultProblemLoader.load(DefaultProblemLoader.java:168)
	at de.uka.ilkd.key.proof.io.ProblemLoader.doWork(ProblemLoader.java:58)
	at de.uka.ilkd.key.proof.io.ProblemLoader.access$000(ProblemLoader.java:32)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:104)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:97)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: de.uka.ilkd.key.speclang.translation.SLTranslationException: unexpected token: elect2 (antlr.NoViableAltException)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.unaryexpr(KeYJMLParser.java:3307)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.multexpr(KeYJMLParser.java:3163)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.additiveexpr(KeYJMLParser.java:3117)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.shiftexpr(KeYJMLParser.java:2935)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.relationalexpr(KeYJMLParser.java:2719)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.equalityexpr(KeYJMLParser.java:2652)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.equalityexpr(KeYJMLParser.java:2659)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.andexpr(KeYJMLParser.java:2521)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.logicalandexpr(KeYJMLParser.java:2465)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.logicalandexpr(KeYJMLParser.java:2471)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.logicalandexpr(KeYJMLParser.java:2471)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.logicalandexpr(KeYJMLParser.java:2471)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.exclusiveorexpr(KeYJMLParser.java:2590)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.inclusiveorexpr(KeYJMLParser.java:2407)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.logicalorexpr(KeYJMLParser.java:2303)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.impliesexpr(KeYJMLParser.java:2212)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.equivalenceexpr(KeYJMLParser.java:2164)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.conditionalexpr(KeYJMLParser.java:2113)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.assignmentexpr(KeYJMLParser.java:2102)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.expression(KeYJMLParser.java:1609)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.termexpression(KeYJMLParser.java:1565)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.top(KeYJMLParser.java:505)
	at de.uka.ilkd.key.speclang.jml.translation.JMLTranslator.translate(JMLTranslator.java:1649)
	at de.uka.ilkd.key.speclang.jml.translation.JMLSpecFactory.createJMLLoopInvariant(JMLSpecFactory.java:1309)
	at de.uka.ilkd.key.speclang.jml.translation.JMLSpecFactory.createJMLLoopInvariant(JMLSpecFactory.java:1373)
	at de.uka.ilkd.key.speclang.jml.JMLSpecExtractor.extractLoopInvariant(JMLSpecExtractor.java:626)
	at de.uka.ilkd.key.speclang.SLEnvInput.createSpecs(SLEnvInput.java:303)
	at de.uka.ilkd.key.speclang.SLEnvInput.read(SLEnvInput.java:373)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.readEnvInput(ProblemInitializer.java:339)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:519)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:468)
	at de.uka.ilkd.key.proof.io.DefaultProblemLoader.createInitConfig(DefaultProblemLoader.java:234)
	at de.uka.ilkd.key.proof.io.DefaultProblemLoader.load(DefaultProblemLoader.java:140)
	... 10 more

```

### Additional Information

```
I ran into this on my Gnome 2.x, Ubuntu 11.10 system.


```

## Files

  
![Bildschirmfoto-Parser_Messages](/uploads/7a9e58b860a2c9fbbdbc01275768e4f9/Bildschirmfoto-Parser_Messages.png)
  

  
![Bildschirmfoto-Parser_Messages-1](/uploads/9d5b28a0b8acf72cb0477dd03864334c/Bildschirmfoto-Parser_Messages-1.png)
  

## History

* (at)mulbrich -- (`NEW_BUG`) _2014-06-26_

* (at)mulbrich -- (`FILE_ADDED`) _2014-06-26_

* (at)mulbrich -- (`FILE_ADDED`) _2014-06-26_

## Attributes

* Category: GUI
* Status: NEW
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: SOMETIMES
* Platform: 
* Commit: e3b73fb73e0e42824ced06f56e4419a9502c9e28
* Build: 
* Tags []
* Labels:  ~GUI  ~Bug  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1457)
    
----
    
Information: 
* created_at: 2017-05-29T03:02:35.679Z
* updated_at: 2017-05-29T03:02:35.911Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
The exception dialog was rewritten some time ago.
