### ISSUE TITLE
Tests cases on `stable`  are not Windows-compatible

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1544]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1544) where the discussions are preserved.
    
----
    
We have two failing test cases on [Windows Azure Pipeline](https://dev.azure.com/keyproject/key/_build/results?buildId=6&view=ms.vss-test-web.build-test-results-tab) on the `stable` branch with  the following exception:

[Stacktrace](https://dev.azure.com/keyproject/key/_test/analytics?definitionId=1&contextType=build)
```
java.nio.file.FileSystemException: D:\a\1\s\key\key.core\src\test\resources\testcase\proofBundle\complexBundleGeneration\test.zproof: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
```

It seems our resource (file) management is not correct.

---

Additionally, multiple `DirectoryNotEmptyException`s are thrown, but it seems that their are catched:
```
java.nio.file.DirectoryNotEmptyException: C:\Users\VSSADM~1\AppData\Local\Temp\KeYTmpFileRepo3945581889229446476
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:266)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
```
    
----
    
Information: 
* created_at: 2020-09-02T15:49:07.480Z
* updated_at: 2021-02-03T07:48:02.432Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 3

**Comment by FliegendeWurst** [comment]
Tests were re-enabled in #3110
