### ISSUE TITLE
Exception when using the same for loop variable name multiple times

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1629]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1629) where the discussions are preserved.

                ----

                ## Description
Using the same loop variable name for multiple loops in a function throws an exception when used in combination with a JML specification.

## Reproducible
This throws an exception:
```
/*@
  @ loop_invariant 0 <= i && i <= values.length;
  @*/
for (int i = 0; i < values.length; ++i) {
}

/*@
  @ loop_invariant 0 <= i && i <= values.length;
  @*/
for (int i = 0; i < values.length; ++i) {
}
```

And for some reason this one as well:
```
/*@
  @ loop_invariant 0 <= i && i <= values.length;
  @*/
for (int i = 0; i < values.length; ++i) {
}

for (int i = 0; i < values.length; ++i) {
}

/*@
  @ loop_invariant 0 <= j && j <= values.length;
  @*/
for (int j = 0; j < values.length; ++j) {
}
```

But this one does not throw:
```
/*@
  @ loop_invariant 0 <= i && i <= values.length;
  @*/
for (int i = 0; i < values.length; ++i) {
}

for (int i = 0; i < values.length; ++i) {
}
```

### Additional information
<details><summary>Click to expand</summary>

```
java.lang.RuntimeException: Name already in namespace: i
	at de.uka.ilkd.key.logic.Namespace.addSafely(Namespace.java:126)
	at de.uka.ilkd.key.speclang.translation.SLResolverManager.putIntoTopLocalVariablesNamespace(SLResolverManager.java:257)
	at de.uka.ilkd.key.speclang.translation.SLResolverManager.putIntoTopLocalVariablesNamespace(SLResolverManager.java:286)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.<init>(KeYJMLParser.java:389)
	at de.uka.ilkd.key.speclang.jml.translation.KeYJMLParser.<init>(KeYJMLParser.java:433)
	at de.uka.ilkd.key.speclang.jml.translation.JMLTranslator.translate(JMLTranslator.java:1830)
	at de.uka.ilkd.key.speclang.jml.translation.JMLSpecFactory.translateToTermInvariants(JMLSpecFactory.java:169)
	at de.uka.ilkd.key.speclang.jml.translation.JMLSpecFactory.createJMLLoopInvariant(JMLSpecFactory.java:1530)
	at de.uka.ilkd.key.speclang.jml.translation.JMLSpecFactory.createJMLLoopInvariant(JMLSpecFactory.java:1638)
	at de.uka.ilkd.key.speclang.jml.JMLSpecExtractor.extractLoopInvariant(JMLSpecExtractor.java:796)
	at de.uka.ilkd.key.speclang.SLEnvInput.addLoopInvariants(SLEnvInput.java:191)
	at de.uka.ilkd.key.speclang.SLEnvInput.createSpecs(SLEnvInput.java:345)
	at de.uka.ilkd.key.speclang.SLEnvInput.read(SLEnvInput.java:389)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.readEnvInput(ProblemInitializer.java:390)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:565)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:521)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.createInitConfig(AbstractProblemLoader.java:501)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.load(AbstractProblemLoader.java:259)
	at de.uka.ilkd.key.proof.io.ProblemLoader.doWork(ProblemLoader.java:78)
	at de.uka.ilkd.key.proof.io.ProblemLoader.access$000(ProblemLoader.java:38)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:124)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:117)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

</details>

---

KeY Version 2.8.0 (internal: 3ddfc1d216)

                ----

                Information: 
                    * created_at: 2021-12-07T12:36:12.033Z
                    * updated_at: 2021-12-13T11:18:29.727Z
                    * closed_at: 2021-12-13T11:18:29.724Z  (closed_by: wiesler)
                    * milestone: 
                    * user_notes_count: 1

**Comment by FliegendeWurst** [comment]
Duplicate of #120
