### ISSUE TITLE
KeY can get into unstable state where proofs cannot be abandoned.

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1632]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1632) where the discussions are preserved.
    
----
    
## Description

I managed to reach state where proofs could no longer be abandoned (ctrl-w).

## Reproducible

sometimes

### Steps to reproduce 

not known.

Ctrl-w does not do anything. ... But a stacktrace on the console.

### Additional information

<details><summary>Stacktrace</summary>

````
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at de.uka.ilkd.key.proof.Proof.removeRuleAppListener(Proof.java:1230)
        at de.uka.ilkd.key.core.KeYMediator.setProofHelper(KeYMediator.java:314)
        at de.uka.ilkd.key.core.KeYMediator.setProof(KeYMediator.java:298)
        at de.uka.ilkd.key.gui.TaskTree.problemChosen(TaskTree.java:172)
        at de.uka.ilkd.key.gui.TaskTree.access$000(TaskTree.java:49)
        at de.uka.ilkd.key.gui.TaskTree$TaskTreeMouseListener.mouseClicked(TaskTree.java:251)
        at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
...
````

</details>

---

* Commit: d1312353ea47596344b550a7d27155c6c03a10d1 for %"v2.10.0"
    
----
    
Information: 
* created_at: 2021-12-07T15:56:42.918Z
* updated_at: 2021-12-08T12:00:20.220Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 4

**Comment by FliegendeWurst** [comment]
Not reproducible. Gitlab comments suggest this only happens when disposing a proof twice which should not be possible unless some *other* bug occurs.
