### ISSUE TITLE
Concurrency issue when autopilot is started multiple times

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#1668]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/1668) where the discussions are preserved.
    
----
    

## Description
Autopilot or Close provable goals can be started multiple times by using the shortcuts while it is already running (or when the GUI is overloaded with big proofs and lags).
This causes the GUI to hang forever without CPU usage.

This should never happen and I think blocking the shortcuts is not enough since there might be other paths to reproduce this issue.
Futhermore, this looks to me like two threads are modifying the same proof tree which is a massive concurrency issue. Is the tree not protected by a lock if it is to be shared between the GUI and proof thread?

## Reproducible

always

### Steps to reproduce 
Load any proof, Full Auto Pilot, use the Close provable goals shortcut while it is running.

Stacktraces:
The console gets spammed with many, I don't know which one is relevant.

<details><summary>Click to expand</summary>

```
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 1
        at org.key_project.util.collection.ImmutableArray.get(ImmutableArray.java:72)
        at de.uka.ilkd.key.logic.TermImpl.sub(TermImpl.java:186)
        at de.uka.ilkd.key.logic.PosInTerm.getSubTerm(PosInTerm.java:216)
        at de.uka.ilkd.key.logic.PosInOccurrence.subTerm(PosInOccurrence.java:208)
        at de.uka.ilkd.key.strategy.termProjection.FocusProjection.toTerm(FocusProjection.java:51)
        at de.uka.ilkd.key.strategy.feature.ApplyTFFeature.computeCost(ApplyTFFeature.java:69)
        at de.uka.ilkd.key.strategy.feature.ShannonFeature.computeCost(ShannonFeature.java:65)
        at de.uka.ilkd.key.strategy.feature.SumFeature.computeCost(SumFeature.java:35)
        at de.uka.ilkd.key.strategy.feature.RuleSetDispatchFeature.computeCost(RuleSetDispatchFeature.java:57)
        at de.uka.ilkd.key.strategy.feature.SumFeature.computeCost(SumFeature.java:40)
        at de.uka.ilkd.key.strategy.JavaCardDLStrategy.computeCost(JavaCardDLStrategy.java:2768)
        at de.uka.ilkd.key.strategy.TacletAppContainer.createContainer(TacletAppContainer.java:78)
        at de.uka.ilkd.key.strategy.TacletAppContainer.createContainer(TacletAppContainer.java:215)
        at de.uka.ilkd.key.strategy.TacletAppContainer.createFurtherApps(TacletAppContainer.java:107)
        at de.uka.ilkd.key.strategy.QueueRuleApplicationManager.computeNextRuleApp(QueueRuleApplicationManager.java:300)
        at de.uka.ilkd.key.strategy.QueueRuleApplicationManager.peekNext(QueueRuleApplicationManager.java:206)
        at de.uka.ilkd.key.strategy.QueueRuleApplicationManager.next(QueueRuleApplicationManager.java:216)
        at de.uka.ilkd.key.prover.impl.ApplyStrategy.applyAutomaticRule(ApplyStrategy.java:103)
        at de.uka.ilkd.key.prover.impl.ApplyStrategy.doWork(ApplyStrategy.java:145)
        at de.uka.ilkd.key.prover.impl.ApplyStrategy.executeStrategy(ApplyStrategy.java:284)
        at de.uka.ilkd.key.prover.impl.ApplyStrategy.start(ApplyStrategy.java:252)
        at de.uka.ilkd.key.macros.TryCloseMacro.applyTo(TryCloseMacro.java:184)
        at de.uka.ilkd.key.macros.AbstractProofMacro.applyTo(AbstractProofMacro.java:89)
        at de.uka.ilkd.key.gui.ProofMacroWorker.doInBackground(ProofMacroWorker.java:102)
        at de.uka.ilkd.key.gui.ProofMacroWorker.doInBackground(ProofMacroWorker.java:40)
        at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
de.uka.ilkd.key.util.AssertionFailure:
Assertion failure: Formula Term subterm: [0,0,0,1,1] of all{b:int}(imp(and(leq(b,add(Z(neglit(1(#))),de_wiesler_Sorter_PartitionResult_num_buckets_0<<selectSK>>)),geq(b,Z(0(#)))),equals(de.wiesler.Sorter::isBucketPartitioned(heapAfter_partition,values,begin,end,int::select(heapAfter_partition,x_arr_2,arr(b)),int::select(heapAfter_partition,x_arr_2,arr(add(Z(1(#)),b)))),TRUE)))<<origin(ensures @ file Sorter.java @ line 95) ([])>> does not exist
        at de.uka.ilkd.key.util.Debug.fail(Debug.java:319)
        at de.uka.ilkd.key.strategy.FindTacletAppContainer.<init>(FindTacletAppContainer.java:66)
        at de.uka.ilkd.key.strategy.TacletAppContainer.createContainer(TacletAppContainer.java:93)
        at de.uka.ilkd.key.strategy.TacletAppContainer.createContainer(TacletAppContainer.java:77)
        at de.uka.ilkd.key.strategy.TacletAppContainer.createAppContainers(TacletAppContainer.java:267)
        at de.uka.ilkd.key.strategy.RuleAppContainer.createAppContainer(RuleAppContainer.java:82)
        at de.uka.ilkd.key.strategy.RuleAppContainer.createAppContainers(RuleAppContainer.java:101)
        at de.uka.ilkd.key.strategy.QueueRuleApplicationManager.rulesAdded(QueueRuleApplicationManager.java:142)
        at de.uka.ilkd.key.proof.RuleAppIndex.informNewRuleListener(RuleAppIndex.java:449)
        at de.uka.ilkd.key.proof.RuleAppIndex$1.rulesAdded(RuleAppIndex.java:113)
        at de.uka.ilkd.key.proof.TermTacletAppIndex.fireRulesAdded(TermTacletAppIndex.java:729)
        at de.uka.ilkd.key.proof.TermTacletAppIndex.addTacletsHelp(TermTacletAppIndex.java:283)
        at de.uka.ilkd.key.proof.TermTacletAppIndex.addTacletsSubIndices(TermTacletAppIndex.java:302)
        at de.uka.ilkd.key.proof.TermTacletAppIndex.addTacletsHelp(TermTacletAppIndex.java:277)
        at de.uka.ilkd.key.proof.TermTacletAppIndex.addTacletsSubIndices(TermTacletAppIndex.java:302)
        at de.uka.ilkd.key.proof.TermTacletAppIndex.addTacletsHelp(TermTacletAppIndex.java:277)
        at de.uka.ilkd.key.proof.TermTacletAppIndex.addTacletsSubIndices(TermTacletAppIndex.java:302)
        at de.uka.ilkd.key.proof.TermTacletAppIndex.addTacletsHelp(TermTacletAppIndex.java:277)
        at de.uka.ilkd.key.proof.TermTacletAppIndex.addTacletsSubIndices(TermTacletAppIndex.java:302)
        at de.uka.ilkd.key.proof.TermTacletAppIndex.addTacletsHelp(TermTacletAppIndex.java:277)
        at de.uka.ilkd.key.proof.TermTacletAppIndex.addTacletsSubIndices(TermTacletAppIndex.java:302)
        at de.uka.ilkd.key.proof.TermTacletAppIndex.addTacletsHelp(TermTacletAppIndex.java:277)
        at de.uka.ilkd.key.proof.TermTacletAppIndex.addTaclets(TermTacletAppIndex.java:266)
        at de.uka.ilkd.key.proof.SemisequentTacletAppIndex.addTaclets(SemisequentTacletAppIndex.java:111)
        at de.uka.ilkd.key.proof.SemisequentTacletAppIndex.addTaclets(SemisequentTacletAppIndex.java:306)
        at de.uka.ilkd.key.proof.TacletAppIndex.updateIndices(TacletAppIndex.java:378)
        at de.uka.ilkd.key.proof.TacletAppIndex.addedNoPosTacletApp(TacletAppIndex.java:417)
        at de.uka.ilkd.key.proof.RuleAppIndex.addNoPosTacletApp(RuleAppIndex.java:351)
        at de.uka.ilkd.key.proof.Goal.addNoPosTacletApp(Goal.java:462)
        at de.uka.ilkd.key.proof.Goal.addTaclet(Goal.java:480)
        at de.uka.ilkd.key.rule.executor.javadl.TacletExecutor.applyAddrule(TacletExecutor.java:371)
        at de.uka.ilkd.key.rule.executor.javadl.FindTacletExecutor.apply(FindTacletExecutor.java:129)
        at de.uka.ilkd.key.rule.Taclet.apply(Taclet.java:912)
        at de.uka.ilkd.key.rule.TacletApp.execute(TacletApp.java:422)
        at de.uka.ilkd.key.proof.Goal.apply(Goal.java:677)
        at de.uka.ilkd.key.prover.impl.ApplyStrategy.applyAutomaticRule(ApplyStrategy.java:125)
        at de.uka.ilkd.key.prover.impl.ApplyStrategy.doWork(ApplyStrategy.java:145)
        at de.uka.ilkd.key.prover.impl.ApplyStrategy.executeStrategy(ApplyStrategy.java:284)
        at de.uka.ilkd.key.prover.impl.ApplyStrategy.start(ApplyStrategy.java:252)
        at de.uka.ilkd.key.macros.TryCloseMacro.applyTo(TryCloseMacro.java:184)
        at de.uka.ilkd.key.macros.AbstractProofMacro.applyTo(AbstractProofMacro.java:89)
        at de.uka.ilkd.key.macros.SequentialProofMacro.applyTo(SequentialProofMacro.java:115)
        at de.uka.ilkd.key.macros.AbstractProofMacro.applyTo(AbstractProofMacro.java:89)
        at de.uka.ilkd.key.gui.ProofMacroWorker.doInBackground(ProofMacroWorker.java:102)
        at de.uka.ilkd.key.gui.ProofMacroWorker.doInBackground(ProofMacroWorker.java:40)
        at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

</details>

### Additional information
* Commit: 666bcb0c95d451b4d1b2a2eaf683625bfbee210e
* Windows 10 Education Version 1909
    
----
    
Information: 
* created_at: 2022-01-09T16:41:37.695Z
* updated_at: 2022-01-12T10:42:30.289Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 1

**Comment by FliegendeWurst** [comment]
I think this is covered by #3200
