### ISSUE TITLE
Uncaught Exception when applying rule known_dynamic_array_type

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#201]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/201) where the discussions are preserved.
    
----
    
* Mantis: [MT-1266](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1266)
* Submitted on: 2013-01-18 by (at)greiner
* Updated: 2013-06-05

### Description

> When a small specification error is made, like requireing "\typeof(bs) == \type(B)", where b is of type B[], an uncaught exception is thrown. (See additional information)
> 
> 

### Steps to reproduce

```
Load the attached files and try to automatically proof A.test()
```

### Additional Information

```
Error Message:


        at de.uka.ilkd.key.gui.KeYMediator.applyInteractive(KeYMediator.java:481)
        at de.uka.ilkd.key.gui.KeYMediator.selectedTaclet(KeYMediator.java:413)
        at de.uka.ilkd.key.gui.KeYMediator.selectedTaclet(KeYMediator.java:375)
        at de.uka.ilkd.key.gui.nodeviews.SequentView.selectedTaclet(SequentView.java:546)
        at de.uka.ilkd.key.gui.nodeviews.TacletMenu$MenuControl.actionPerformed(TacletMenu.java:467)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6505)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
        at java.awt.Component.processEvent(Component.java:6270)
        at java.awt.Container.processEvent(Container.java:2229)
        at java.awt.Component.dispatchEventImpl(Component.java:4861)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4687)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2713)
        at java.awt.Component.dispatchEvent(Component.java:4687)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:707)
        at java.awt.EventQueue.access$000(EventQueue.java:101)
        at java.awt.EventQueue$3.run(EventQueue.java:666)
        at java.awt.EventQueue$3.run(EventQueue.java:664)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.awt.EventQueue$4.run(EventQueue.java:680)
        at java.awt.EventQueue$4.run(EventQueue.java:678)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:677)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:211)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

## Files

  
[src.tar.gz](/uploads/73f43351f12e9172e29a5bf121a76aff/src.tar.gz)
  

## History

* (at)greiner -- (`NEW_BUG`) _2013-01-18_

* (at)greiner -- (`FILE_ADDED`) _2013-01-18_

* (at)grahl -- (`BUGNOTE_ADDED`) _2013-06-05_

* (at)grahl -- (`BUGNOTE_DELETED`) _2013-06-05_

## Attributes

* Category: Prover Core
* Status: NEW
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: LOW
* Reproducibility: ALWAYS
* Platform: 
* Commit: 2.0
* Build: 
* Tags []
* Labels:  ~Prover Core  ~Bug  ~LOW  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1266)
    
----
    
Information: 
* created_at: 2017-05-29T02:31:48.155Z
* updated_at: 2017-05-29T02:31:48.155Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Fixed in #3216 or earlier
