### ISSUE TITLE
Empty parser error message

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#266]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/266) where the discussions are preserved.
    
----
    
* Mantis: [MT-1517](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1517)
* Submitted on: 2014-12-12 by (at)klebanov
* Updated: 2014-12-19

### Description

> I had a .key file where the java block in a modality was broken. The loader shows an EMPTY error dialog titled de.uka.ilkd.key.proof.init.ProofInputException.
> 
> Clicking on "show details" shows a completely useless stacktrace - the useful error message is swallowed by the system and never shown to the user. See additional information attached to this report.

### Additional Information

```
The useful error message that is swallowed:
de.uka.ilkd.key.java.PosConvertException: Could not resolve UncollatedReferenceQualifier "SHA1PRNG_SecureRandomImpl" (at)1/2 in INTERNAL://<virtual_class_for_parsing129> (07b)

Instead the following is shown (after expanding details):
(class de.uka.ilkd.key.proof.init.ProofInputException)
de.uka.ilkd.key.proof.init.ProofInputException
	at de.uka.ilkd.key.proof.io.KeYFile.read(KeYFile.java:357)
	at de.uka.ilkd.key.proof.init.KeYUserProblemFile.read(KeYUserProblemFile.java:112)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.readEnvInput(ProblemInitializer.java:350)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:525)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:481)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.createInitConfig(AbstractProblemLoader.java:345)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.load(AbstractProblemLoader.java:192)
	at de.uka.ilkd.key.proof.io.ProblemLoader.doWork(ProblemLoader.java:72)
	at de.uka.ilkd.key.proof.io.ProblemLoader.access$000(ProblemLoader.java:36)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:118)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:111)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: org.antlr.runtime.RecognitionException
	at de.uka.ilkd.key.parser.KeYParser.getJavaBlock(KeYParser.java:1245)
	at de.uka.ilkd.key.parser.KeYParser.modality_dl_term(KeYParser.java:9578)
	at de.uka.ilkd.key.parser.KeYParser.unary_formula(KeYParser.java:5987)
	at de.uka.ilkd.key.parser.KeYParser.term60(KeYParser.java:5893)
	at de.uka.ilkd.key.parser.KeYParser.conjunction_term(KeYParser.java:5812)
	at de.uka.ilkd.key.parser.KeYParser.disjunction_term(KeYParser.java:5748)
	at de.uka.ilkd.key.parser.KeYParser.implication_term(KeYParser.java:5690)
	at de.uka.ilkd.key.parser.KeYParser.equivalence_term(KeYParser.java:5626)
	at de.uka.ilkd.key.parser.KeYParser.elementary_update_term(KeYParser.java:5566)
	at de.uka.ilkd.key.parser.KeYParser.term(KeYParser.java:5500)
	at de.uka.ilkd.key.parser.KeYParser.formula(KeYParser.java:5460)
	at de.uka.ilkd.key.parser.KeYParser.problem(KeYParser.java:14665)
	at de.uka.ilkd.key.proof.io.KeYFile.read(KeYFile.java:338)
	... 16 more

```

## Notes

_(at)grahl at 2014-12-19_
> Where does PosConvertException occur? Please attach the complete stack trace.

## Associated Bugs

* Relates to MT-1486 with 

## History

* (at)klebanov -- (`NEW_BUG`) _2014-12-12_

* (at)grahl -- (`BUGNOTE_ADDED`) _2014-12-19_

* (at)grahl -- (`BUG_ADD_RELATIONSHIP`) _2014-12-19_

## Attributes

* Category: Parser
* Status: NEW
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: dcb72af55997ee60457ee8bb7095978cc4f960ac
* Build: 
* Tags []
* Labels:  ~KeY Parser  ~Bug  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1517)
    
----
    
Information: 
* created_at: 2017-05-29T02:33:18.461Z
* updated_at: 2017-05-29T02:33:18.461Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by FliegendeWurst** [comment]
Not actionable without the file in question
