### ISSUE TITLE
Doubles cannot be subtracted (user report)

### ISSUE THREAD

**Issue by mattulbrich** [KeYProject/key#3114]
## Description

"Key cannot make a subtract between 2 double"

Submitted by a user using the in-system-report mechanism.

## Reproducible
  
unknown

### Steps to reproduce 

Exception raised on this input
```
package ex2;

public class Car {
 [...]

    /*@ requires fuelVolume >= 0;
        requires (tankCapacity - fuelTank) >= fuelVolume;
        ensures fuelTank == (\old(fuelTank) + fuelVolume);
        assignable fuelTank;
     */
    public void refuel(double fuelVolume){
        fuelTank = fuelTank + fuelVolume;
    }

    /*@ requires distance > 0 && distance <= fuelTank / fuelCunsumption;
        ensures fuelTank == \old(fuelTank) - distance * fuelCunsumption;
        ensures distanceTraveled == \old(distanceTraveled) + distance;
        assignable distanceTraveled, fuelTank;
     */
    public void travel(double distance){
        distanceTraveled += distance;
        fuelTank -= distance * fuelCunsumption;
    }
[...}
}
```

### Additional information

```
java.lang.RuntimeException: de.uka.ilkd.key.speclang.translation.SLTranslationException: Error in subtract expression double::select(heap,self,ex2.Car::$tankCapacity)(type: (type, sort): (double,double)) - double::select(heap,self,ex2.Car::$fuelTank)(type: (type, sort): (double,double)).
	at de.uka.ilkd.key.speclang.njml.JmlTermFactory.substract(JmlTermFactory.java:671)
	at de.uka.ilkd.key.speclang.njml.Translator.visitAdditiveexpr(Translator.java:686)
	at de.uka.ilkd.key.speclang.njml.JmlParser$AdditiveexprContext.accept(JmlParser.java:7649)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:125)
	at de.uka.ilkd.key.speclang.njml.Translator.lambda$mapOf$0(Translator.java:129)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[...]
Caused by: de.uka.ilkd.key.speclang.translation.SLTranslationException: Error in subtract expression double::select(heap,self,ex2.Car::$tankCapacity)(type: (type, sort): (double,double)) - double::select(heap,self,ex2.Car::$fuelTank)(type: (type, sort): (double,double)).
	at de.uka.ilkd.key.speclang.translation.SLExceptionFactory.createException(SLExceptionFactory.java:203)
	at de.uka.ilkd.key.speclang.translation.SLExceptionFactory.createException(SLExceptionFactory.java:223)
	at de.uka.ilkd.key.speclang.translation.JavaIntegerSemanticsHelper.raiseError(JavaIntegerSemanticsHelper.java:65)
	at de.uka.ilkd.key.speclang.translation.JavaIntegerSemanticsHelper.buildSubExpression(JavaIntegerSemanticsHelper.java:236)
	at de.uka.ilkd.key.speclang.njml.JmlTermFactory.substract(JmlTermFactory.java:669)
	... 229 more
Caused by: java.lang.RuntimeException: Could not determine promoted type of double and double
	at de.uka.ilkd.key.java.TypeConverter.getPromotedType(TypeConverter.java:453)
	at de.uka.ilkd.key.speclang.translation.JavaIntegerSemanticsHelper.getPromotedType(JavaIntegerSemanticsHelper.java:70)
	at de.uka.ilkd.key.speclang.translation.JavaIntegerSemanticsHelper.buildSubExpression(JavaIntegerSemanticsHelper.java:225)
	... 230 more
```

---

* Commit: 2.10.0 (internal: 666bcb0c95)

**Comment by mattulbrich** [comment]
This has been resolved since and is no longer observable on current main (623a20e6c7a489dba37f7e0cd3ab89cd19d2ea09).
