### ISSUE TITLE
Recursive model method cannot be parsed any longer

### ISSUE THREAD

**Issue by mattulbrich** [KeYProject/key#3118]
## Description

Recursive model methods seem not to be parsed any more.

The following example does not longer parse, although it should:
```java
class A {
    /*@ model_behaviour requires true;
      @  model instance int fac(int n) { return n <= 0 ? 1 : fac(n-1) * n; } */
    
    /*@ normal_behaviour
      @ requires m == 0;
      @ ensures \result == fac(m);
      @*/
    int f(int m) {
       return 1;
    }
}
```

## Reproducible
  
always

### Steps to reproduce 

Try to load the above code. It should load (and actually prove `f` automatically).

#### Stacktrace
```
Method fac(<unknown type>, \bigint) not found! at /tmp/k/A.java:3:65 (/tmp/k/A.java:3:65)
	at de.uka.ilkd.key.speclang.njml.Translator.raiseError(Translator.java:2544)
	at de.uka.ilkd.key.speclang.njml.Translator.visitPrimarySuffixCall(Translator.java:1033)
	at de.uka.ilkd.key.speclang.njml.JmlParser$PrimarySuffixCallContext.accept(JmlParser.java:8985)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.visitPostfixexpr(Translator.java:858)
	at de.uka.ilkd.key.speclang.njml.Translator.visitPostfixexpr(Translator.java:63)
	at de.uka.ilkd.key.speclang.njml.JmlParser$PostfixexprContext.accept(JmlParser.java:8315)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.visitUnaryexprnotplusminus(Translator.java:840)
	at de.uka.ilkd.key.speclang.njml.JmlParser$UnaryexprnotplusminusContext.accept(JmlParser.java:8146)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.oneOf(Translator.java:147)
	at de.uka.ilkd.key.speclang.njml.Translator.visitUnaryexpr(Translator.java:800)
	at de.uka.ilkd.key.speclang.njml.Translator.visitUnaryexpr(Translator.java:63)
	at de.uka.ilkd.key.speclang.njml.JmlParser$UnaryexprContext.accept(JmlParser.java:8002)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.lambda$mapOf$0(Translator.java:133)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at de.uka.ilkd.key.speclang.njml.Translator.mapOf(Translator.java:133)
	at de.uka.ilkd.key.speclang.njml.Translator.visitMultexpr(Translator.java:737)
	at de.uka.ilkd.key.speclang.njml.JmlParser$MultexprContext.accept(JmlParser.java:7921)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.lambda$mapOf$0(Translator.java:133)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at de.uka.ilkd.key.speclang.njml.Translator.mapOf(Translator.java:133)
	at de.uka.ilkd.key.speclang.njml.Translator.visitAdditiveexpr(Translator.java:720)
	at de.uka.ilkd.key.speclang.njml.JmlParser$AdditiveexprContext.accept(JmlParser.java:7829)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.lambda$mapOf$0(Translator.java:133)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at de.uka.ilkd.key.speclang.njml.Translator.mapOf(Translator.java:133)
	at de.uka.ilkd.key.speclang.njml.Translator.visitShiftexpr(Translator.java:703)
	at de.uka.ilkd.key.speclang.njml.JmlParser$ShiftexprContext.accept(JmlParser.java:7742)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.oneOf(Translator.java:147)
	at de.uka.ilkd.key.speclang.njml.Translator.visitRelationalexpr(Translator.java:494)
	at de.uka.ilkd.key.speclang.njml.JmlParser$RelationalexprContext.accept(JmlParser.java:7344)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.lambda$mapOf$0(Translator.java:133)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at de.uka.ilkd.key.speclang.njml.Translator.mapOf(Translator.java:133)
	at de.uka.ilkd.key.speclang.njml.Translator.visitEqualityexpr(Translator.java:562)
	at de.uka.ilkd.key.speclang.njml.Translator.visitEqualityexpr(Translator.java:63)
	at de.uka.ilkd.key.speclang.njml.JmlParser$EqualityexprContext.accept(JmlParser.java:7270)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.visitAndexpr(Translator.java:544)
	at de.uka.ilkd.key.speclang.njml.JmlParser$AndexprContext.accept(JmlParser.java:7201)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.visitExclusiveorexpr(Translator.java:529)
	at de.uka.ilkd.key.speclang.njml.JmlParser$ExclusiveorexprContext.accept(JmlParser.java:7132)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.visitInclusiveorexpr(Translator.java:514)
	at de.uka.ilkd.key.speclang.njml.JmlParser$InclusiveorexprContext.accept(JmlParser.java:7063)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.visitLogicalandexpr(Translator.java:501)
	at de.uka.ilkd.key.speclang.njml.JmlParser$LogicalandexprContext.accept(JmlParser.java:6994)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.visitLogicalorexpr(Translator.java:482)
	at de.uka.ilkd.key.speclang.njml.Translator.visitLogicalorexpr(Translator.java:63)
	at de.uka.ilkd.key.speclang.njml.JmlParser$LogicalorexprContext.accept(JmlParser.java:6925)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.visitImpliesexpr(Translator.java:446)
	at de.uka.ilkd.key.speclang.njml.JmlParser$ImpliesexprContext.accept(JmlParser.java:6662)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.lambda$mapOf$0(Translator.java:133)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at de.uka.ilkd.key.speclang.njml.Translator.mapOf(Translator.java:133)
	at de.uka.ilkd.key.speclang.njml.Translator.visitEquivalenceexpr(Translator.java:426)
	at de.uka.ilkd.key.speclang.njml.JmlParser$EquivalenceexprContext.accept(JmlParser.java:6585)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.visitConditionalexpr(Translator.java:412)
	at de.uka.ilkd.key.speclang.njml.Translator.visitConditionalexpr(Translator.java:63)
	at de.uka.ilkd.key.speclang.njml.JmlParser$ConditionalexprContext.accept(JmlParser.java:6516)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.visitConditionalexpr(Translator.java:417)
	at de.uka.ilkd.key.speclang.njml.Translator.visitConditionalexpr(Translator.java:63)
	at de.uka.ilkd.key.speclang.njml.JmlParser$ConditionalexprContext.accept(JmlParser.java:6516)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.visitExpression(Translator.java:402)
	at de.uka.ilkd.key.speclang.njml.Translator.visitExpression(Translator.java:63)
	at de.uka.ilkd.key.speclang.njml.JmlParser$ExpressionContext.accept(JmlParser.java:6463)
	at de.uka.ilkd.key.speclang.njml.Translator.accept(Translator.java:128)
	at de.uka.ilkd.key.speclang.njml.Translator.visitMethod_declaration(Translator.java:2358)
	at de.uka.ilkd.key.speclang.njml.Translator.visitMethod_declaration(Translator.java:63)
	at de.uka.ilkd.key.speclang.njml.JmlParser$Method_declarationContext.accept(JmlParser.java:3990)
	at de.uka.ilkd.key.speclang.njml.JmlIO.interpret(JmlIO.java:178)
	at de.uka.ilkd.key.speclang.njml.JmlIO.translateTerm(JmlIO.java:188)
	at de.uka.ilkd.key.speclang.njml.JmlIO.translateTerm(JmlIO.java:214)
	at de.uka.ilkd.key.speclang.jml.translation.JMLSpecFactory.translateAndClauses(JMLSpecFactory.java:558)
	at de.uka.ilkd.key.speclang.jml.translation.JMLSpecFactory.translateEnsures(JMLSpecFactory.java:682)
	at de.uka.ilkd.key.speclang.jml.translation.JMLSpecFactory.translateAxioms(JMLSpecFactory.java:422)
	at de.uka.ilkd.key.speclang.jml.translation.JMLSpecFactory.translateJMLClauses(JMLSpecFactory.java:367)
	at de.uka.ilkd.key.speclang.jml.translation.JMLSpecFactory.createJMLOperationContracts(JMLSpecFactory.java:1144)
	at de.uka.ilkd.key.speclang.jml.JMLSpecExtractor.extractMethodSpecs(JMLSpecExtractor.java:476)
	at de.uka.ilkd.key.speclang.SLEnvInput.createSpecs(SLEnvInput.java:314)
	at de.uka.ilkd.key.speclang.SLEnvInput.read(SLEnvInput.java:361)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.readEnvInput(ProblemInitializer.java:334)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:558)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:458)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.createInitConfig(AbstractProblemLoader.java:549)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.loadEnvironment(AbstractProblemLoader.java:311)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.load(AbstractProblemLoader.java:275)
	at de.uka.ilkd.key.proof.io.ProblemLoader.doWork(ProblemLoader.java:64)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:117)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:110)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

#### git-bisect
git-bisecting of the problem was difficult as there are many commits that do not compile, unfortunately.

The problem can be narrowed down to the following commits:
```
Method fac(<unknown type>, \bigint) not found! at /tmp/k/A.java:3:64 (/tmp/k/A.java:3:64)
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
70bb4fcc8dd535c0dd2bd93f4ec52cc363618ecb
8e3184559225de427a9c17bcb3cc279cc73e3dfa
90737a8fbbc1173f8f143d36f0ff78861a9da9f7
fae2579074e553e9e5781b51bf13e138cc71082a
034f83920572c064bf03b71615d551c2a2eb4360
04512a8f6a27177fe802ca1ec08c0fc567ccd7ed
5e23b81faeefdb1c0126f2db904ab8bf9d777bbc
af579feb754a607ab37603f70407f3fc854ea3b1
187612f7e60e4c329eb020b6101e5879674f6b41
57c7506c5832eba6cade3b09ef9aff371ad87fd8
a5e412a9e1485b3e19293e478cc117c2049138a3
aec2daeb56a26ba51425cadf5d3c153d1d184888
592d15c515ba9fe4355de8e46e9c1e141b09819b
e574028af19864dd23f4795a756c431fdf57e8f8
37cf507fae09063a1bf5796e197fee2aa33f9e67
38697ea616e655877685aa0228fb74dd430f6870
022b8bb3f8c3a4932de0c8cea1c88c3e7707d0dc
2c4572757d5336d9c6fc904e8a3cf6d59f9c2233
136797c93c849bd3dff74775f969c2df48cf4ee1
e3418609e3c12cb41c4fd680b368d53fe7c3ff24
3d8496a2c8bfd4e8e98b98d99b5e2f6b524478e1
d012e9e47c77ad3fc61138e76fd0b8b95d4462d0
46c63561fc1cf3f28a291282944eb80c3897e8c2
cdd59f3fa4b108467304e242cf6dde36c58ddd2f
382db84b45b09ddd34fc1e537cf457297747f10a
57ce827495f81c91170d39245885b1e8ccef4920
4bd54837689cdfff0ca2d384050d2c1e249d63ec
548ad70278d7cbd4957dbd21552005f4e19e55cf
901b2608e28447f503d085d178e18c5d7b6f3350
d38760719b88cdebd5522a76116fa20920537e1b
86024b11202d280e4199da511901793dda3a0e56
c1d8b7cce9d72230371d1fe7fb7541d8d4f7f1be
0a0e3ce13861bda4452d6018f2e8ffa388a554bd
6f96ed1e39057d34eabae6762a037a909fa163a3
3e721258ea2d1ba8264e2651afe08e5a9b31a06a
474c5cf2a3378b884f2ac76de8176209a8e60e10
2b2a501678d265721c798737a184e866cba4c1d6
869974c799d715dfee30b3857a1b3fbbf8fbc86c
6b4af48eadbc5b6a0600f659c79d5a71198b81c0
e852cb49c67d1c815e2560a2932da4abce60d17e
4e4ec1c8037575962d4a70133e27080c9e61077b
bee6ec50bc4be101fde03bd85667f5007f07e3c1
e7ba160287933232bb344341e39062660c0617e6
f99274224d16428b491e4a450abf1b669d552eff
159f55ee080a64229b2f4c0d1c4673cf979f7fab
81054b5d20873a16a0cff7c8edc994582f9d6d70
b1728f51c7fd2994f76a394dabcf3bc8147a9361
bf5897842e2462f891c7c2b90a7960e430001508
486f9da7a05f17d9ac6608768a7eb60500a270bd
c3535a45a54ef89f5d62e60503d96dfb6d81dcd0
27565e4bd7fe8dbe82959fb70a0562bce6c0d529
3317a3a0f897913b1ca41fdfcea09b1f4ef25779
5d45e4f51d41b9843fb523e49d119d9de1247fdd
f06d8d1afc046153c77badf18bd6be4fd10fc82d
63d4106e0fbcdb1aa4cb60551e093501cbe787c7
7cb8657f6dafda50c8bc2389d8f385c2078dfba6
2a4c2900280c31afaade74e128883625a5be7cf1
2f704937f25f6e5455dc249759bc40ab130d93ed
0ad202c2644841e89d96b6dec8a7737184b9b566
be2fb67dab8eb5c2ee6f074342fc30530f64c507
3d304b5af003bc962b1ffbdf29e26c56c075f689
We cannot bisect more!
```

Most of them are by @jwiesler, a few by @unp1 

---

* Commit: 8b1702985a172ab4be4b44140b2c508f8a43a64d

**Comment by mattulbrich** [comment]
Mmmh. On 2nd glance, this might even be desired behaviour. (Is it?) Quite unexpected, I's say.

**Comment by jwiesler** [comment]
Yes, it is desired. Default spec math mode is bigint, `n - 1` is of type `\bigint` and you are calling a method that requires an `int` which is a narrowing conversion requiring a cast.
The function resolution error descriptions are horrible (read *non-existant*).

Replacing the type of the parameter (and best the return type as well) with `\bigint` removes all issues.

**Comment by mattulbrich** [comment]
Unfortunately, this is the new default behaviour (according to JML). You could add `/*@ spec_safe_math */` to the class such that int are used as bigints w/o modulo operators.
