### ISSUE TITLE
Index out of bounds in error dialog if more than one schema variable

### ISSUE THREAD

**Issue by mattulbrich** [KeYProject/key#3156]
## Description

Something is wrong (since recently) with the error reporting from the taclet instantiation dialogue.

## Reproducible
always

### Steps to reproduce 
1. Load the Contraposition example
2. Do a cut on `bsum{int i;}(0, 4, i * i) = 42`
3. Apply the rule `bsum_split` on one of the occurrences of the bsum.
4. Enter `heap` (sic!) in the instantiation for middle.
5. Press `Apply`.

Observe the error message: `Index 4 out of bounds for length 1`

KeY should complain that heap is not an integer.

The example has nothing to do with bsums. The point is that the taclet instantation window must have more than one entry and that an input error occurs in one of the lower fields.

### Additional information

<details><summary>Stacktrace</summary>
```
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 1
	at de.uka.ilkd.key.proof.SVInstantiationParserException.getMessage(SVInstantiationParserException.java:37)
	at de.uka.ilkd.key.control.instantiation_model.TacletInstantiationModel.getStatusString(TacletInstantiationModel.java:178)
	at de.uka.ilkd.key.gui.TacletMatchCompletionDialog$DataTable.editingStopped(TacletMatchCompletionDialog.java:522)
	at java.desktop/javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:152)
	at de.uka.ilkd.key.gui.TacletMatchCompletionDialog$DataTable$InputEditor.fireEditingStopped(TacletMatchCompletionDialog.java:638)
	at java.desktop/javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:375)
	at java.desktop/javax.swing.DefaultCellEditor.stopCellEditing(DefaultCellEditor.java:234)
	at de.uka.ilkd.key.gui.TacletMatchCompletionDialog.pushAllInputToModel(TacletMatchCompletionDialog.java:208)
	at de.uka.ilkd.key.gui.TacletMatchCompletionDialog.pushAllInputToModel(TacletMatchCompletionDialog.java:200)
	at de.uka.ilkd.key.gui.TacletMatchCompletionDialog$ButtonListener.actionPerformed(TacletMatchCompletionDialog.java:309)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
...

```
</details>

* Commit: 470b0d67e179aefc5995d4bb1c0bcd0da7654cb8

**Comment by mattulbrich** [comment]
Julian @jwiesler, I assigned this to you since you authored the commit hat last touched the line that throws the exception.

**Comment by jwiesler** [comment]
This has nothing to do with my changes, if you look at the diff you can see that I only renamed a function.

I'll look into it anyways.
