### ISSUE TITLE
Fresh installation: NullpointerException

### ISSUE THREAD

**Issue by unp1** [KeYProject/key#3238]
## Description

While testing for the KeY 2.12.0 release on macOS, I experienced the following issue in case of a fresh installation (removal of the ~/.key config directory):

Reloading via (CMD+R) failed with a NullPointerException see stacktrace in section "Additional Information".

## Reproducible

Always.  
> Is the issue reproducible?
> Select one of: always, sometimes, random, have not tried, n/a 

### Steps to reproduce 

> Describe the steps needed to reproduce the issue.

1. Delete the config directory (~/.key)
2. Start KeY and load an example
3. Exit KeY
4. Restart KeY
5. Reload via CMD+R (or CTRL+R on non macOS systems)

**Note** that step 3 is necessary as reloading while not having exited KeY works as expected.

> What is your expected behavior and what was the actual behavior?

I would have expected that the most recent opened problem would be reloaded instead an NPE is thrown.

I expect that there are actually two issues at play:

1. Exiting KeY does not save the most recent files list
2. Triggering "reload of most recent problem" via a keyboard shortcut is possible, while the menu entry is grayed out. The reload action should not allow to be triggered when not enabled. 

### Additional information

 java.lang.NullPointerException: Cannot invoke "de.uka.ilkd.key.gui.RecentFileMenu$RecentFileEntry.getAbsolutePath()" because "this.mostRecentFile" is null
	at de.uka.ilkd.key.gui.RecentFileMenu.getMostRecent(RecentFileMenu.java:236)
	at de.uka.ilkd.key.gui.actions.OpenMostRecentFileAction.actionPerformed(OpenMostRecentFileAction.java:34)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:354)
---

* Commit: 0013f6905bec83ee9a3aead24cce9231d4a22148

**Comment by mattulbrich** [comment]
+1

**Comment by mattulbrich** [comment]
May be fixed already in fix for #3214 where the problem has also been reported.

**Comment by unp1** [comment]
Hi,
 thanks a lot for the pointer! I tried the latest associated branch commit 8272547 and it is not yet fixed there. The recentFiles.prop not being generated and causing an exception is different from this bug manifestation.
