### ISSUE TITLE
StackOverflowError when searching in large sequent

### ISSUE THREAD

**Issue by FliegendeWurst** [KeYProject/key#3261]
## Description

When searching in a large sequent, a StackOverflowError is printed to stderr.

<details>

```
Exception in thread "AWT-EventQueue-0" java.lang.StackOverflowError
        at java.base/java.util.regex.Pattern$Slice.match(Pattern.java:4088)
        at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
        at java.base/java.util.regex.Pattern$Slice.match(Pattern.java:4088)
        at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
        at java.base/java.util.regex.Pattern$Slice.match(Pattern.java:4088)
        at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
        at java.base/java.util.regex.Pattern$Slice.match(Pattern.java:4088)
        at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
        at java.base/java.util.regex.Pattern$Slice.match(Pattern.java:4088)
        at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
        at java.base/java.util.regex.Pattern$Slice.match(Pattern.java:4088)
        at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
        at java.base/java.util.regex.Pattern$Slice.match(Pattern.java:4088)
        at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
        at java.base/java.util.regex.Pattern$Slice.match(Pattern.java:4088)
        at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
        at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3955)
        at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4329)
[...]
```
</details>

## Reproducible
  
sometimes

### Steps to reproduce 

I will get a copy of the offending sequent once I can get the issue to reproduce.

Expected: search works or handles the error gracefully

**Comment by FliegendeWurst** [comment]
I think it may be necessary to use something like https://github.com/google/re2j instead of plain Java Regex
