### ISSUE TITLE
TacletAppIndex or TermTacletAppIndex becomes corrupted

### ISSUE THREAD

**Issue by unp1** [KeYProject/key#3313]
## Description

> Please describe your concern in detail!

Proof search leads to exception

## Reproducible
  
> Is the issue reproducible?
> Select one of: always, sometimes, random, have not tried, n/a 

always

### Steps to reproduce 

> Describe the steps needed to reproduce the issue.

1. Load A.java ([A.java.zip](https://github.com/KeYProject/key/files/13058931/A.java.zip))
2. Ensure that Taclet Option: methodExpansion:noRestriction is activated (activate and reload file if necessary)
3. Select the PO for method toProve
4. Strategy Settings: Switch Method Treatment to None
5. Start the automation -> stops at method inc()
6. Apply method inlining (rule methodCall) for inc() manually
7. Restart the automation
8. Try to apply the operation contract rule for dec()
9. Result: Exception

> What is your expected behavior and what was the actual behavior?

No exception and being able to close the proof.

### Additional information

> Add more details here. In particular: if you have a stacktrace, put it here.

---

* Commit: ca0c52224ad45e8d7e98f8674c4f088caa7ff483

**Comment by FliegendeWurst** [comment]
The full stacktrace is below. It does look very similar to #3259.

<details>

```
Exception in thread "AWT-EventQueue-0" de.uka.ilkd.key.util.AssertionFailure: 
Assertion failure: Formula Term subterm: [0,0,0,0,0] of update-application(parallel-upd(parallel-upd(parallel-upd(elem-update(heapAtPre)(heap),elem-update(exc)(null)),elem-update(a)(self)),elem-update(a_1)(self<<origin(<none> (implicit)) ([ensures @ file A.java @ line 20, ensures (implicit), assignable (implicit), assignable @ file A.java @ line 21])>>)<<origin(<none> (implicit)) ([ensures @ file A.java @ line 20, ensures (implicit), assignable (implicit), assignable @ file A.java @ line 21])>>)<<origin(<none> (implicit)) ([ensures @ file A.java @ line 20, ensures (implicit), assignable (implicit), assignable @ file A.java @ line 21])>>,\<{
  try {
    method-frame (source=toProve()@A, this=self) {
      {
        method-frame (source=inc()@A, this=self) {
          int i_2;
          i_2 = a.x;
          i_1 = i_2 + 1;
          i = (int) i_1;
          a_1.x = i;
        }
      }
      dec();
    }
  } catch (java.lang.Throwable e) {
    exc = e;
  }
}\> (and(and(and(equals(int::select(heapAtPre,self,A::$x),int::select(heap,self,A::$x))<<origin(ensures @ file A.java @ line 20) ([])>>,java.lang.Object::<inv>(heap,self)<<impl>>)<<SC, origin(ensures @ file A.java @ line 20) ([ensures @ file A.java @ line 20])>>,equals(exc<<origin(ensures (implicit)) ([])>>,null)<<impl, origin(ensures (implicit)) ([ensures (implicit)])>>)<<origin(<none> (implicit)) ([ensures @ file A.java @ line 20, ensures (implicit)])>>,all{f:Field}(all{o:java.lang.Object}(or(or(and(equals(o,self<<origin(assignable (implicit)) ([])>>)<<origin(assignable (implicit)) ([assignable (implicit)])>>,equals(f,A::$x)<<origin(assignable (implicit)) ([])>>)<<origin(assignable (implicit)) ([assignable (implicit)])>>,and(not(equals(o,null)<<origin(assignable (implicit)) ([])>>)<<origin(assignable (implicit)) ([assignable (implicit)])>>,not(equals(boolean::select(heapAtPre,o,java.lang.Object::<created>),TRUE)<<origin(assignable (implicit)) ([])>>)<<origin(assignable (implicit)) ([assignable (implicit)])>>)<<origin(assignable (implicit)) ([assignable (implicit)])>>)<<origin(assignable (implicit)) ([assignable (implicit)])>>,equals(any::select(heapAtPre,o,f),any::select(heap,o,f))<<origin(assignable (implicit)) ([])>>)<<origin(assignable (implicit)) ([assignable (implicit)])>>)<<origin(assignable (implicit)) ([assignable (implicit)])>>)<<origin(assignable (implicit)) ([assignable (implicit)])>>)<<origin(<none> (implicit)) ([ensures @ file A.java @ line 20, ensures (implicit), assignable (implicit)])>>)<<origin(<none> (implicit)) ([ensures @ file A.java @ line 20, ensures (implicit), assignable (implicit)])>>)<<origin(<none> (implicit)) ([ensures @ file A.java @ line 20, ensures (implicit), assignable (implicit), assignable @ file A.java @ line 21])>> does not exist
	at de.uka.ilkd.key.util.Debug.fail(Debug.java:105)
	at de.uka.ilkd.key.strategy.FindTacletAppContainer.<init>(FindTacletAppContainer.java:52)
	at de.uka.ilkd.key.strategy.TacletAppContainer.createContainer(TacletAppContainer.java:69)
	at de.uka.ilkd.key.strategy.TacletAppContainer.createInitialAppContainers(TacletAppContainer.java:197)
	at de.uka.ilkd.key.strategy.RuleAppContainer.createAppContainers(RuleAppContainer.java:116)
	at de.uka.ilkd.key.strategy.QueueRuleApplicationManager.rulesAdded(QueueRuleApplicationManager.java:139)
	at de.uka.ilkd.key.proof.RuleAppIndex.informNewRuleListener(RuleAppIndex.java:364)
	at de.uka.ilkd.key.proof.RuleAppIndex$1.rulesAdded(RuleAppIndex.java:57)
	at de.uka.ilkd.key.proof.TermTacletAppIndex.fireRulesAdded(TermTacletAppIndex.java:598)
	at de.uka.ilkd.key.proof.TermTacletAppIndex.createHelp(TermTacletAppIndex.java:186)
	at de.uka.ilkd.key.proof.TermTacletAppIndex.createSubIndices(TermTacletAppIndex.java:134)
	at de.uka.ilkd.key.proof.TermTacletAppIndex.createHelp(TermTacletAppIndex.java:184)
	at de.uka.ilkd.key.proof.TermTacletAppIndex.createSubIndices(TermTacletAppIndex.java:134)
	at de.uka.ilkd.key.proof.TermTacletAppIndex.createHelp(TermTacletAppIndex.java:184)
	at de.uka.ilkd.key.proof.TermTacletAppIndex.createSubIndices(TermTacletAppIndex.java:134)
	at de.uka.ilkd.key.proof.TermTacletAppIndex.createHelp(TermTacletAppIndex.java:184)
	at de.uka.ilkd.key.proof.TermTacletAppIndex.createSubIndices(TermTacletAppIndex.java:134)
	at de.uka.ilkd.key.proof.TermTacletAppIndex.createHelp(TermTacletAppIndex.java:184)
	at de.uka.ilkd.key.proof.TermTacletAppIndex.createSubIndices(TermTacletAppIndex.java:134)
	at de.uka.ilkd.key.proof.TermTacletAppIndex.createHelp(TermTacletAppIndex.java:184)
	at de.uka.ilkd.key.proof.TermTacletAppIndex.create(TermTacletAppIndex.java:156)
	at de.uka.ilkd.key.proof.SemisequentTacletAppIndex.addTermIndex(SemisequentTacletAppIndex.java:57)
	at de.uka.ilkd.key.proof.SemisequentTacletAppIndex.updateTermIndices(SemisequentTacletAppIndex.java:134)
	at de.uka.ilkd.key.proof.SemisequentTacletAppIndex.updateTermIndices(SemisequentTacletAppIndex.java:150)
	at de.uka.ilkd.key.proof.SemisequentTacletAppIndex.sequentChanged(SemisequentTacletAppIndex.java:220)
	at de.uka.ilkd.key.proof.TacletAppIndex.deltaUpdateIndices(TacletAppIndex.java:178)
	at de.uka.ilkd.key.proof.TacletAppIndex.update(TacletAppIndex.java:162)
	at de.uka.ilkd.key.proof.TacletAppIndex.getIndex(TacletAppIndex.java:202)
	at de.uka.ilkd.key.proof.TacletAppIndex.getFindTaclet(TacletAppIndex.java:302)
	at de.uka.ilkd.key.proof.RuleAppIndex.getFindTaclet(RuleAppIndex.java:188)
	at de.uka.ilkd.key.control.AbstractProofControl.getFindTaclet(AbstractProofControl.java:133)
	at de.uka.ilkd.key.gui.nodeviews.CurrentGoalViewListener.mouseClicked(CurrentGoalViewListener.java:76)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "de.uka.ilkd.key.proof.TermTacletAppIndex.getTacletAppAt(de.uka.ilkd.key.logic.PosInOccurrence, de.uka.ilkd.key.proof.rulefilter.RuleFilter)" because the return value of "de.uka.ilkd.key.proof.SemisequentTacletAppIndex.getTermIndex(de.uka.ilkd.key.logic.PosInOccurrence)" is null
	at de.uka.ilkd.key.proof.SemisequentTacletAppIndex.getTacletAppAt(SemisequentTacletAppIndex.java:194)
	at de.uka.ilkd.key.proof.TacletAppIndex.getFindTaclet(TacletAppIndex.java:302)
	at de.uka.ilkd.key.proof.RuleAppIndex.getFindTaclet(RuleAppIndex.java:188)
	at de.uka.ilkd.key.control.AbstractProofControl.getFindTaclet(AbstractProofControl.java:133)
	at de.uka.ilkd.key.gui.nodeviews.CurrentGoalViewListener.mouseClicked(CurrentGoalViewListener.java:76)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
```

</details>
