### ISSUE TITLE
Model methods cannot be used in ghost or set statements

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#398]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/398) where the discussions are preserved.
    
----
    
* Mantis: [MT-1601](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1601)
* Submitted on: 2017-05-15 by (at)mkirsten
* Updated: 2017-05-15

### Description

> When you execute a model method or apply its contract inside a set or ghost statement, an NPE is thrown (see additional information) with the attached stack trace.

### Steps to reproduce

```
Load the attached example and try to prove it.
```

### Additional Information

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at de.uka.ilkd.key.util.Assert.assertEqualSort(Assert.java:41)
	at de.uka.ilkd.key.speclang.FunctionalOperationContractImpl.getReplaceMap(FunctionalOperationContractImpl.java:333)
	at de.uka.ilkd.key.speclang.FunctionalOperationContractImpl.getPost(FunctionalOperationContractImpl.java:1135)
	at de.uka.ilkd.key.speclang.FunctionalOperationContractImpl.getPost(FunctionalOperationContractImpl.java:1156)
	at de.uka.ilkd.key.rule.UseOperationContractRule.apply(UseOperationContractRule.java:729)
	at de.uka.ilkd.key.rule.AbstractBuiltInRuleApp.execute(AbstractBuiltInRuleApp.java:79)
	at de.uka.ilkd.key.proof.Goal.apply(Goal.java:648)
	at de.uka.ilkd.key.control.AbstractProofControl.selectedBuiltInRule(AbstractProofControl.java:377)
	at de.uka.ilkd.key.gui.nodeviews.TacletMenu$MenuControl.actionPerformed(TacletMenu.java:561)
	at de.uka.ilkd.key.gui.nodeviews.MenuItemForTwoModeRules$1.actionPerformed(MenuItemForTwoModeRules.java:63)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

## Files

  
`Test.java`:

```java
public final class Test {

    //@ public static ghost int num = 1;

    /*@ public static model_behaviour
      @ assignable \strictly_nothing;
      @ ensures \result == 0;
      @ public static model int zero() {
      @     return 0;
      @ }
      @*/

    /*@ public static normal_behaviour
      @ assignable num;
      @ ensures \result == zero();
      @ ensures \result == num;
      @*/
    public static /*@ helper @*/ int test(int number) {
	//@ set num = zero();
	return 0;
    }
}

```

## History

* (at)mkirsten -- (`NEW_BUG`) _2017-05-15_

* (at)mkirsten -- (`FILE_ADDED`) _2017-05-15_

## Attributes

* Category: Calculus
* Status: NEW
* Severity: BLOCK
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: 467fb64a50710e1ed3ba8248bcd38c24b5c673f0
* Build: 
* Tags []
* Labels:  ~Calculus  ~Bug  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1601)
    
----
    
Information: 
* created_at: 2017-05-29T02:36:36.003Z
* updated_at: 2022-10-13T12:20:49.513Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 0

**Comment by mattulbrich** [comment]
While this fixed the assignment of model *methods*, model *fields* still raise a differentexception if assigned to ghost fields/vars.

Let's fix this, while we are on it ...

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at de.uka.ilkd.key.java.TypeConverter.convertToLogicElement(TypeConverter.java:334)
	at de.uka.ilkd.key.java.TypeConverter.convertToLogicElement(TypeConverter.java:301)
	at de.uka.ilkd.key.java.TypeConverter.convertReferencePrefix(TypeConverter.java:180)
	at de.uka.ilkd.key.java.TypeConverter.convertToLogicElement(TypeConverter.java:319)
	at de.uka.ilkd.key.rule.inst.SVInstantiations.getTermInstantiation(SVInstantiations.java:411)
	at de.uka.ilkd.key.rule.SyntacticalReplaceVisitor.visit(SyntacticalReplaceVisitor.java:289)
	at de.uka.ilkd.key.logic.TermImpl.execPostOrder(TermImpl.java:264)
	at de.uka.ilkd.key.logic.TermImpl.execPostOrder(TermImpl.java:261)
	at de.uka.ilkd.key.logic.TermImpl.execPostOrder(TermImpl.java:261)
	at de.uka.ilkd.key.logic.TermImpl.execPostOrder(TermImpl.java:261)
	at de.uka.ilkd.key.rule.executor.javadl.TacletExecutor.syntacticalReplace(TacletExecutor.java:87)
	at de.uka.ilkd.key.rule.executor.javadl.TacletExecutor.instantiateReplacement(TacletExecutor.java:135)
	at de.uka.ilkd.key.rule.executor.javadl.TacletExecutor.instantiateSemisequent(TacletExecutor.java:168)
	at de.uka.ilkd.key.rule.executor.javadl.TacletExecutor.replaceAtPos(TacletExecutor.java:194)
	at de.uka.ilkd.key.rule.executor.javadl.SuccTacletExecutor.applyReplacewith(SuccTacletExecutor.java:34)
	at de.uka.ilkd.key.rule.executor.javadl.FindTacletExecutor.apply(FindTacletExecutor.java:104)
	at de.uka.ilkd.key.rule.Taclet.apply(Taclet.java:935)
	at de.uka.ilkd.key.rule.TacletApp.execute(TacletApp.java:349)
	at de.uka.ilkd.key.proof.Goal.apply(Goal.java:624)
