### ISSUE TITLE
Obsolote / broken examples

### ISSUE THREAD

**Issue by wadoon** [KeYProject/key#54]
This issue was created at [git.key-project.org](https://git.key-project.org/key/key/-/issues/54) where the discussions are preserved.
    
----
    
* Mantis: [MT-1572](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1572)
* Submitted on: 2015-09-16 by (at)most
* Updated: 2015-09-16

### Description

> The examples directory contains examples that are outdated / not working. One example is the TreeMax competition challenge from FOVEOOS 2011 that uses \set that is currently not supported (not sure if only syntactically or all together).

## History

* (at)most -- (`NEW_BUG`) _2015-09-16_

* (at)mkirsten -- (`BUGNOTE_ADDED`) _2015-09-16_

* (at)mkirsten -- (`BUGNOTE_DELETED`) _2015-09-16_

## Attributes

* Category: Proof Loading/Saving
* Status: NEW
* Severity: MINOR
* OS: 
* Target Version: 
* Resolution: OPEN
* Priority: NORMAL
* Reproducibility: ALWAYS
* Platform: 
* Commit: 613b41a56970c2cc33e0185011b381894c401574
* Build: 
* Tags []
* Labels:  ~Proof Loading/Saving  ~Bug  ~NORMAL  

---

[View in Mantis](http://i12www.ira.uka.de/~klebanov/mantis/view.php?id=1572)
    
----
    
Information: 
* created_at: 2017-05-29T02:27:49.157Z
* updated_at: 2021-08-10T15:07:34.444Z
* closed_at: None  (closed_by: )
* milestone: 
* user_notes_count: 1

**Comment by wadoon** [comment]
<img width="967" height="535" alt="Image" src="https://github.com/user-attachments/assets/935ed203-1d9c-4c0d-82b3-6cf0d7f36c53" />

```stacktrace
JavaBuildingExceptions{issues=[JavaBuildingIssue{node=\setrange=Optional[(line 1,col 1)-(line 1,col 4)], message='Unresolved KeY type'}]}
	at de.uka.ilkd.key.java.loader.JP2KeYVisitor.reportError(JP2KeYConverter.java:147)
	at de.uka.ilkd.key.java.loader.JP2KeYVisitor.visit(JP2KeYConverter.java:427)
	at de.uka.ilkd.key.java.loader.JP2KeYVisitor.visit(JP2KeYConverter.java:119)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.accept(ClassOrInterfaceType.java:136)
	at de.uka.ilkd.key.java.loader.JP2KeYVisitor.accept(JP2KeYConverter.java:383)
	at de.uka.ilkd.key.java.loader.JP2KeYVisitor.requireTypeReference(JP2KeYConverter.java:157)
	at de.uka.ilkd.key.java.loader.JP2KeYVisitor.visit(JP2KeYConverter.java:801)
	at de.uka.ilkd.key.java.loader.JP2KeYVisitor.visit(JP2KeYConverter.java:119)
	at com.github.javaparser.ast.body.FieldDeclaration.accept(FieldDeclaration.java:128)
	at de.uka.ilkd.key.java.loader.JP2KeYVisitor.map(JP2KeYConverter.java:460)
	at de.uka.ilkd.key.java.loader.JP2KeYVisitor.visit(JP2KeYConverter.java:349)
	at de.uka.ilkd.key.java.loader.JP2KeYVisitor.visit(JP2KeYConverter.java:119)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:248)
	at de.uka.ilkd.key.java.loader.JP2KeYVisitor.map(JP2KeYConverter.java:460)
	at de.uka.ilkd.key.java.loader.JP2KeYVisitor.visit(JP2KeYConverter.java:440)
	at de.uka.ilkd.key.java.loader.JP2KeYVisitor.visit(JP2KeYConverter.java:119)
	at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:136)
	at de.uka.ilkd.key.java.loader.JP2KeYConverter.process(JP2KeYConverter.java:114)
	at de.uka.ilkd.key.java.loader.JP2KeYConverter.processCompilationUnit(JP2KeYConverter.java:100)
	at de.uka.ilkd.key.java.JavaService.readCompilationUnits(JavaService.java:339)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.readJava(ProblemInitializer.java:282)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:617)
	at de.uka.ilkd.key.proof.init.ProblemInitializer.prepare(ProblemInitializer.java:483)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.createInitConfig(AbstractProblemLoader.java:554)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.loadEnvironment(AbstractProblemLoader.java:348)
	at de.uka.ilkd.key.proof.io.AbstractProblemLoader.load(AbstractProblemLoader.java:307)
	at de.uka.ilkd.key.proof.io.ProblemLoader.doWork(ProblemLoader.java:74)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:124)
	at de.uka.ilkd.key.proof.io.ProblemLoader$1.doInBackground(ProblemLoader.java:117)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:303)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:340)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
```

```java
public final class Tree {

    int value;
    /*@ nullable @*/ Tree left;
    /*@ nullable @*/ Tree right;

    /*@ invariant left == null <==> right == null;
      @ invariant left != null ==> 
      @                   (\invariant_for(left) && \invariant_for(right));
      @*/

    /*@ ghost int height;
      @ invariant height >= 0;
      @ invariant left != null ==>
      @                   height > left.height && height > right.height;
      @*/

    /*@ ghost \set values;
      @ invariant values == \dl_cup(\dl_single(value),
      @           (left==null)? \dl_emptySet()
      @                       : \dl_cup(left.values,right.values));
      @*/

    /*@ normal_behavior
      @ ensures (\forall int z; \dl_contains(z,values); z <= \result);
      @ ensures \dl_contains(\result,values);
      @ measured_by height;
      @ strictly_pure
      @*/
    int max () {
        int res = value;
        if (left != null) {
            res = maxHelper(res,left.max(),right.max());
        }
        return res;
    }

    /*@ normal_behavior
      @ ensures \result >= x;
      @ ensures \result >= y;
      @ ensures \result >= z;
      @ ensures \result == x || \result == y || \result == z;
      @ strictly_pure helper
      @*/
    int maxHelper(int x, int y, int z) {
        if (x > y) return (x > z? x: z);
        else return (y > z? y: z);
    }
}
```
